### ISSUE TITLE
Forced Hosts

### ISSUE THREAD

**Issue by gp-Airee** [mchostco/Droplet#1]
So, I noticed that you allow us to have forced hosts.

But theres no way to specify what host we want. I have mc.airee.ga pointing to minehut, alas no 3rd party server. It'd be impossible for it to know which server to connect to.

**Comment by MatrixTunnel** [comment]
Luuke is working on a fix for this.  If you notice in the [DropletBukkit.java on line #50](https://github.com/mchostco/Droplet/blob/master/plugin/bukkit/src/main/java/com/minehut/droplet/bukkit/DropletBukkit.java#L50) he has a config option for adding the servers ip. (It's added but not working yet) If I guess correctly, he is going to make the domain that you point to minehut point to the server using that ip somehow. 

Again, I'm guessing here, but I think the forced hosts option is only for Minehut. If players could change this and they use any other ip, they could connect to the server not using a Minehut connection and it could be a security breach for the server if they don't know how to set it up. (And you couldn't go back to hub)

**Comment by lukechatton** [comment]
The problem right now is finding a good way to authenticate that a droplet server owner actually owns the domain they put in the config. 

Our dynamic join system will read find a match for the domain name provided when a user either connect to the Minehut proxy.

Let's say there is a popular server named `kitpvp.org` that is setup as a Minehut third party server. Then another server owner decides to put `kitpvp.org` in their `config.yml`, even though they obviously don't own it. This would cause issues when the proxy attempts to query our database for a matching domain field for the server object.

I believe the best way to handle this is to setup some tools to allow certain Minehut staff members to assign domains to servers on request. This will hopefully get prioritized sometime soon.

**Comment by gp-Airee** [comment]
How about a CNAME to a actual minehut.me and make minehut.me subdomains
work?

**Comment by lukechatton** [comment]
This won't solve anything when it comes time for the proxy to find the correct server to point the connection towards.

**Comment by gp-Airee** [comment]
How so? It would have the server name in the CNAME record, and minehut
could determine what server to direct it to through that.

**Comment by gp-Airee** [comment]
This doesn't matter to me anyways, my server, Asylum, has it's own
BungeeCord for direct connection now.

**Comment by lukechatton** [comment]
Just be aware, we will most likely be blocking connections not coming from Minehut in the future. However, we won't do that until we get a solid domain direct connection system in full effect.

**Comment by gp-Airee** [comment]
How exactly do you plan to do this?

**Comment by lukechatton** [comment]
Would be on the droplet bukkit plugin level. I think it’s in our best interest to force players through our proxy if they aren’t using our hosting service. 

Obviously players tampering with the droplet code to remove the minehut-only connection check will have their servers blacklisted from our droplet service as well.

**Comment by gp-Airee** [comment]
That's fair enough. I guess I'll have to stop using Droplet when this is
implemented, thanks for the kickstart on my server, it's been a major help.
Also I noticed you joined my server, haha. Just a shame I wasn't there.

**Comment by gp-Airee** [comment]
Is our proxy affecting Minehut's playercount? We'd be more than happy to
comply with an update to allow our ~20 players on our proxy to show on
Minehut's side.

**Comment by lukechatton** [comment]
It’s currently not. Only connections that go through Minehut’s proxies will change the player count.

**Comment by lukechatton** [comment]
I can manually add your domain right now though. Once updated in our database, Minehut's direct join feature should work with your server.

What is your server name and ip?

**Comment by gp-Airee** [comment]
Asylum - *.asylumcloud.com & asylumcloud.com

**Comment by gp-Airee** [comment]
play.asylumcloud.com in particular

**Comment by lukechatton** [comment]
I have routed `play.asylumcloud.com`, `mc.asylumcloud.com` and `asylumcloud.com`. Just point your domain towards Minehut and the direct join feature should work.

**Comment by gp-Airee** [comment]
Okay.

**Comment by gp-Airee** [comment]
Luuke, I noticed Journey is a third party server.
Is this permitted?
If they paid for it, I'll gladly give you anywhere from 10 to 50 dollars a month for the ability to add my third party server.

**Comment by lukechatton** [comment]
Please send me an email directly at chattonluke@gmail.com. We can discuss getting your server verified on Minehut.
